services:
  - type: web
    name: backend
    env: node
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dhanuvagman69_db_user:NMwqCdmAoXB6b9kA@cluster0.q5pjqrp.mongodb.net/
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: dhanuvagman69@gmail.com
      - key: EMAIL_PASS
        value: wkci slit hjgf aadp
      - key: EMAIL_FROM
        value: "Nordic Retail System"
      - key: PORT
        value: 5000
